import type {WorkSchedule} from '../types/schedule';
import type {Quote,CompanySettings} from '../types/index';
import {estimateSchedule} from './scheduleMath.js';
import {physicalFinancial} from './physicalFinancial.js';
import {measuredQuantity} from './execution.js';
import {sinapiOriginLabel} from './sinapiRegional.js';
const esc=(v: unknown)=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch));
const fmt=(v:number)=>Number.isFinite(v)?v.toLocaleString('pt-BR',{maximumFractionDigits:3}):'—';
const money=(v:number)=>Number.isFinite(v)?v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—';
const date=(v:string|null|undefined)=>v&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v.split('-').reverse().join('/'): 'A definir';
export function buildScheduleDocument(schedule:WorkSchedule,quote?:Quote,company?:CompanySettings):string {
  const report=estimateSchedule(schedule);
  const physical=physicalFinancial(schedule,quote);
  const labels = new Map(schedule.tasks.map((t,i)=>[t.id,`${i+1} · ${t.composition.code}`]));
  const rows=report.entries.map((e,i)=>{
    const deps=(schedule.scheduleMode==='dependencias'?(e.task.dependencies||[]):i?[schedule.tasks[i-1].id]:[]).map(id=>labels.get(id)||'Referência inválida').join(', ');
    const roles=e.labor.map(l=>`${l.role}: ${fmt(l.hours)} HH / ${l.workers||'equipes não informadas'}`).join(' | ');
    return `<tbody class="activity"><tr><td>${i+1}</td><td><b>${esc(e.task.composition.code)}</b> — ${esc(e.task.composition.description)}<small>Composição: ${esc(e.task.composition.sourceFile)} · ${esc(sinapiOriginLabel(e.task.composition))}</small></td><td>${fmt(e.task.quantity)} ${esc(e.task.composition.unit)}</td><td>${fmt(e.totalHH)} HH</td><td>${e.days===null?'Pendente':`${e.days} dias úteis`}</td><td>${date(e.start)} / ${date(e.end)}</td><td>${fmt(measuredQuantity(e.task))} ${esc(e.task.composition.unit)}</td></tr><tr class="note"><td></td><td colspan="6"><span>Equipe: ${esc(roles||'Não informada')}</span>${deps?`<span>Predecessoras: ${esc(deps)}</span>`:''}${e.warnings.length?`<span class="warn">Pendências: ${esc(e.warnings.join(' '))}</span>`:''}</td></tr></tbody>`;
  }).join('');
  const reference = [...new Set(schedule.tasks.map(t=>t.composition.reference).filter(Boolean))].join(', ')||'Não informada';
  const warns=physical.issues.map(w=>`<li>${esc(w)}</li>`).join('');
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cronograma — ${esc(schedule.title)}</title><style>
@page{size:A4;margin:13mm 11mm}*{box-sizing:border-box}html,body{margin:0;background:#07111c;color:#f3f7fc;font-family:Arial,'DejaVu Sans',sans-serif;font-size:11px;line-height:1.45}body{-webkit-print-color-adjust:exact;print-color-adjust:exact;padding:22px}header{border-bottom:2px solid #f97316;padding-bottom:15px;margin-bottom:18px}h1{font-size:22px;margin:0 0 5px}h2{font-size:15px;margin:0 0 10px;color:#fdba74}.sub{color:#a5b4c6}.pill{display:inline-block;padding:4px 9px;background:#372013;color:#fdba74;border-radius:7px;margin-top:8px}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-bottom:18px}.card{padding:10px;border:1px solid #384858;border-radius:10px;background:#101e2d;overflow-wrap:anywhere}.card b{display:block;margin:4px 0;font-size:13px}table{width:100%;border-collapse:collapse;table-layout:fixed}thead{display:table-header-group}th{text-align:left;background:#173048;color:#fed7aa;font-size:10px;padding:7px}td{padding:7px 5px;border-bottom:1px solid #35485b;vertical-align:top;overflow-wrap:anywhere}tr,tbody.activity{break-inside:avoid-page;page-break-inside:avoid}td small{display:block;color:#94a3b8;margin-top:4px}tr.note td{font-size:10px;color:#9cabbc;background:#0e1d2b;padding:5px 8px 10px}.note span{display:block;margin-bottom:3px}.warn{color:#fbbf24}.totals{display:flex;gap:10px;margin:16px 0}.totals .card{flex:1}section{break-inside:auto;margin:14px 0}footer{color:#93a6b9;border-top:1px solid #41516a;padding-top:8px;font-size:10px}.hint{padding:10px 12px;border:1px solid #6a4932;border-radius:9px;color:#fed7aa;margin:10px 0}li{margin-bottom:4px}@media print{html,body{background:#07111c}body{padding:0}.meta{grid-template-columns:repeat(3,1fr)}.card,.hint{break-inside:avoid-page}}
</style></head><body><header><h1>Cronograma de execução</h1><div class="sub">${esc(company?.tradeName||company?.name||'Empresa não identificada')} · ${esc(schedule.title)}</div><div class="pill">${esc((schedule.operationalStatus||'planejamento').replace('_',' '))} · planejamento técnico, não promessa contratual</div></header>
<div class="meta"><div class="card">Orçamento vinculado<b>${esc(quote?.number||'Não informado')}</b>${esc(quote?.clientName||'')}</div><div class="card">Início previsto<b>${date(schedule.startDate)}</b>Término: ${date(report.finishDate)}</div><div class="card">Prazo estimado<b>${report.workingDays===null?'Pendente':`${report.workingDays} dias úteis`}</b>${report.pending} etapa(s) sem cálculo</div><div class="card">Horas-homem<b>${fmt(report.totalHH)} HH</b>SINAPI: ${esc(reference)}</div><div class="card">Jornada e eficiência<b>${fmt(schedule.hoursPerDay)} h/dia · ${fmt(schedule.efficiency*100)}%</b>Valores definidos para a obra</div><div class="card">Calendário<b>${schedule.scheduleMode==='dependencias'?'Com dependências':'Sequencial'}</b>${(schedule.holidays||[]).length} dia(s) não úteis informados</div></div>
<section><h2>Etapas e equipes</h2>${report.entries.length?`<table><thead><tr><th style="width:5%">#</th><th>Composição / serviço</th><th style="width:12%">Quantidade</th><th style="width:10%">HH</th><th style="width:11%">Prazo</th><th style="width:15%">Datas</th><th style="width:12%">Medido</th></tr></thead>${rows}</table>`:'<p>Nenhuma etapa cadastrada.</p>'}</section>
<section><h2>Físico-financeiro dos itens vinculados</h2><div class="totals"><div class="card">Valor vinculado<b>${money(physical.planned)}</b></div><div class="card">Valor proporcional medido<b>${money(physical.measured)}</b></div><div class="card">Avanço dos itens cobertos<b>${physical.percent===null?'Não calculado':`${fmt(physical.percent)}%`}</b></div></div>${warns?`<ul class="sub">${warns}</ul>`:''}</section>
<div class="hint">Este documento apresenta estimativa baseada em coeficientes informados por planilha, equipes e jornada declaradas. Sem rateio automático de recursos compartilhados entre etapas paralelas. As datas devem ser conferidas com feriados locais, logística e condições reais da obra. Valor proporcional medido não é faturamento, nota fiscal ou recebimento.</div>
<footer>OrçaPro · Documento gerado sob demanda com registros disponíveis no sistema. Não contém assinaturas, medições ou equipes inventadas.</footer></body></html>`;
}
